
// This file has been generated by the GUI designer. Do not modify.
namespace MonoMultiJack
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action fileAction;

		private global::Gtk.Action reStartJackdAction;

		private global::Gtk.Action stopJackdAction;

		private global::Gtk.Action stopAllAction;

		private global::Gtk.Action quitAction;

		private global::Gtk.Action ConfigurationAction;

		private global::Gtk.Action configureJackdAction;

		private global::Gtk.Action addRemoveApplicationsAction;

		private global::Gtk.Action helpAction;

		private global::Gtk.Action aboutAction;

		private global::Gtk.VBox mainVbox;

		private global::Gtk.MenuBar menubar1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoMultiJack.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.fileAction = new global::Gtk.Action ("fileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.fileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.fileAction, null);
			this.reStartJackdAction = new global::Gtk.Action ("reStartJackdAction", global::Mono.Unix.Catalog.GetString ("(Re)Start Jackd"), null, "gtk-refresh");
			this.reStartJackdAction.Sensitive = false;
			this.reStartJackdAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("(Re)Start Jackd");
			w1.Add (this.reStartJackdAction, null);
			this.stopJackdAction = new global::Gtk.Action ("stopJackdAction", global::Mono.Unix.Catalog.GetString ("Stop Jackd"), null, "gtk-stop");
			this.stopJackdAction.Sensitive = false;
			this.stopJackdAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Stop Jackd");
			w1.Add (this.stopJackdAction, null);
			this.stopAllAction = new global::Gtk.Action ("stopAllAction", global::Mono.Unix.Catalog.GetString ("Stop All"), null, "gtk-stop");
			this.stopAllAction.Sensitive = false;
			this.stopAllAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Stop All");
			w1.Add (this.stopAllAction, null);
			this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
			this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
			w1.Add (this.quitAction, null);
			this.ConfigurationAction = new global::Gtk.Action ("ConfigurationAction", global::Mono.Unix.Catalog.GetString ("Configuration"), null, null);
			this.ConfigurationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Configuration");
			w1.Add (this.ConfigurationAction, null);
			this.configureJackdAction = new global::Gtk.Action ("configureJackdAction", global::Mono.Unix.Catalog.GetString ("Configure Jackd"), null, "gtk-preferences");
			this.configureJackdAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Configure Jackd");
			w1.Add (this.configureJackdAction, null);
			this.addRemoveApplicationsAction = new global::Gtk.Action ("addRemoveApplicationsAction", global::Mono.Unix.Catalog.GetString ("Add / Remove Applications"), null, "gtk-preferences");
			this.addRemoveApplicationsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add / Remove Applications");
			w1.Add (this.addRemoveApplicationsAction, null);
			this.helpAction = new global::Gtk.Action ("helpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.helpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.helpAction, null);
			this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, "gtk-about");
			this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.aboutAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "MonoMultiJack.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MonoMultiJack.MainWindow.Gtk.Container+ContainerChild
			this.mainVbox = new global::Gtk.VBox ();
			this.mainVbox.Name = "mainVbox";
			// Container child mainVbox.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='fileAction' action='fileAction'><menuitem name='reStartJackdAction' action='reStartJackdAction'/><menuitem name='stopJackdAction' action='stopJackdAction'/><menuitem name='stopAllAction' action='stopAllAction'/><menuitem name='quitAction' action='quitAction'/></menu><menu name='ConfigurationAction' action='ConfigurationAction'><menuitem name='configureJackdAction' action='configureJackdAction'/><menuitem name='addRemoveApplicationsAction' action='addRemoveApplicationsAction'/></menu><menu name='helpAction' action='helpAction'><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.mainVbox.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.mainVbox[this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.mainVbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 275;
			this.DefaultHeight = 175;
			this.Show ();
			this.reStartJackdAction.Activated += new global::System.EventHandler (this.RestartJackd);
			this.stopJackdAction.Activated += new global::System.EventHandler (this.StopJackd);
			this.stopAllAction.Activated += new global::System.EventHandler (this.StopAll);
			this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
			this.configureJackdAction.Activated += new global::System.EventHandler (this.ConfigureJackd);
			this.addRemoveApplicationsAction.Activated += new global::System.EventHandler (this.ConfigureApplications);
			this.aboutAction.Activated += new global::System.EventHandler (this.AboutDialog);
		}
	}
}
